apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    nodePort: 31443
    targetPort: 444
    protocol: TCP
    name: https-internal
  selector:
    app: {{ template "rancher.fullname" . }}
