apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: amf-deployment
  labels:
    nf: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: amf
  template:
    metadata:
      labels:
        nf: amf
    spec:
      hostname: amf
      initContainers:
      - name: init-nrf-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup nrf-service.5gcore.svc.cluster.local; do echo waiting for nrf; sleep 2; done"]
      containers:
      - name: amf
        image: ilyassifez/5gcore:amf
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29518
        command: ["./amf"]
        args: ["-amfcfg", "../config/amfcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/amfcfg.conf
          name: amfcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: amf5gc-volume
      volumes:
      - name: amfcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/amfcfg.conf
      - name: amf5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: amf-service
spec:
  selector:
    nf: amf
  clusterIP: 10.100.244.18
  ports:
    - protocol: TCP
      port: 29518 # Port exposed to the cluster
      targetPort: 29518 # Port on which the pod listens
