apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: mongo-deployment
  labels:
    nf: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: mongo
  template:
    metadata:
      labels:
        nf: mongo
    spec:
      hostname: mongo
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        command: ["mongod"]
        # "--bind_ip","mongo-service.5gcore.svc.cluster.local",
        args: ["--bind_ip_all","--port", "27017"]
        volumeMounts:
        - mountPath: /data/db
          name: dbdata
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: mongo-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: mongo-service
spec:
  selector:
    nf: mongo
  ports:
    - protocol: TCP
      port: 27017 # Port exposed to the cluster
      targetPort: 27017 # Port on which the pod listens
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: 5gcore
  name: mongo-pv
spec:
  volumeMode: Filesystem
  hostPath:
    path: "$HOME/mongo-pv"
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: 5gcore
  name: mongo-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
