apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: nrf-service
spec:
  selector:
    nf: nrf
  ports:
    - protocol: TCP
      port: 29510 # Port exposed to the cluster
      targetPort: 29510 # Port on which the pod listens
