apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: nrf-deployment
  labels:
    nf: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: nrf
  template:
    metadata:
      labels:
        nf: nrf
    spec:
      hostname: nrf
      # initContainers:
      # - name: "wait-for-services"
      #   image: stevenaldinger/docker-k8s-wait-for-it
      #   imagePullPolicy: Always
      #   env:
      #   - name: WAIT_FOR_IT
      #     value: "true"
      #   - name: WAIT_FOR_PODS
      #     value: "mongo-service.5gcore"
      initContainers:
      - name: init-mongo-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mongo-service.5gcore.svc.cluster.local; do echo waiting for mongo; sleep 2; done"]
      containers:
      - name: nrf
        image: ilyassifez/5gcore:nrf
        env:
        - name: DB_URI
          value: mongodb://db/free5gc
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29510
        command: ["./nrf"]
        args: ["-nrfcfg", "../config/nrfcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/nrfcfg.conf
          name: nrfcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: nrf5gc-volume
      volumes:
      - name: nrfcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/nrfcfg.conf
      - name: nrf5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: nrf-service
spec:
  clusterIP: 10.100.244.10
  selector:
    nf: nrf
  ports:
    - port: 29510 # Port exposed to the cluster
      protocol: TCP
      targetPort: 29510 # Port on which the pod listens
