apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: nssf-deployment
  labels:
    nf: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: nssf
  template:
    metadata:
      labels:
        nf: nssf
    spec:
      hostname: nssf
      initContainers:
      - name: init-nrf-service
        image: curlimages/curl:latest
        command: ['sh', '-c', "until curl http://nrf-service.5gcore.svc.cluster.local:29510; do echo waiting for NRF; sleep 2; done"]
      containers:
      - name: nssf
        image: ilyassifez/5gcore:nssf
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29531
        command: ["./nssf"]
        args: ["-nssfcfg", "../config/nssfcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/nssfcfg.conf
          name: nssfcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: nssf5gc-volume
      volumes:
      - name: nssfcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/nssfcfg.conf
      - name: nssf5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: nssf-service
spec:
  clusterIP: 10.244.100.31
  selector:
    nf: nssf
  ports:
    - protocol: TCP
      port: 29531 # Port exposed to the cluster
      targetPort: 29531 # Port on which the pod listens
