apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: smf-deployment
  labels:
    nf: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: smf
  template:
    metadata:
      labels:
        nf: smf
    spec:
      hostname: smf
      initContainers:
      - name: init-nrf-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup nrf-service.5gcore.svc.cluster.local; do echo waiting for nrf; sleep 2; done"]
      containers:
      - name: smf
        image: ilyassifez/5gcore:smf
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29502
        command: ["./smf"]
        args: ["-smfcfg", "../config/smfcfg.conf","-uerouting","../config/uerouting.yaml"]
        volumeMounts:
        - mountPath: /free5gc/config/smfcfg.conf
          name: smfcfg-volume
        - mountPath: /free5gc/config/uerouting.yaml
          name: uerouting-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: smf5gc-volume
      volumes:
      - name: smfcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/smfcfg.conf
      - name: smf5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
      - name: uerouting-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/uerouting.yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: smf-service
spec:
  selector:
    nf: smf
  clusterIP: 10.100.244.2
  ports:
    - protocol: TCP
      port: 29502 # Port exposed to the cluster
      targetPort: 29502 # Port on which the pod listens
