apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: udm-deployment
  labels:
    nf: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: udm
  template:
    metadata:
      labels:
        nf: udm
    spec:
      hostname: udm
      initContainers:
      - name: init-nrf-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup nrf-service.5gcore.svc.cluster.local; do echo waiting for nrf; sleep 2; done"]
      containers:
      - name: udm
        image: ilyassifez/5gcore:udm
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29503
        command: ["./udm"]
        args: ["-udmcfg", "../config/udmcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/udmcfg.conf
          name: udmcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: udm5gc-volume
      volumes:
      - name: udmcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/udmcfg.conf
      - name: udm5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: 5gcore
#   name: udm-service
# spec:
#   selector:
#     nf: udm
#   ports:
#     - protocol: TCP
#       port: 29503 # Port exposed to the cluster
#       targetPort: 29503 # Port on which the pod listens
