apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: udm-deployment
  labels:
    app: udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
    spec:
      hostname: udm
      initContainers:
      - name: init-nrf-service
        image: curlimages/curl:latest
        command: ['sh', '-c', "until curl http://nrf-service.5gcore.svc.cluster.local:29510; do echo waiting for NRF; sleep 2; done"]
      containers:
      - name: udm
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        image: ilyassifez/5gcore:udm
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29503
        command: ["./udm"]
        args: ["-udmcfg", "../config/udmcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/udmcfg.conf
          name: udmcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: udm5gc-volume
      volumes:
      - name: udmcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/udmcfg.conf
      - name: udm5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: udm-service
spec:
  clusterIP: 10.244.100.3
  selector:
    app: udm
  ports:
    - protocol: TCP
      port: 29503 # Port exposed to the cluster
      targetPort: 29503 # Port on which the pod listens
