apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: udm-service
spec:
  selector:
    nf: udm
  ports:
    - protocol: TCP
      port: 29503 # Port exposed to the cluster
      targetPort: 29503 # Port on which the pod listens
