apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: udr-deployment
  labels:
    app: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      hostname: udr
      initContainers:
      - name: init-nrf-service
        image: curlimages/curl:latest
        command: ['sh', '-c', "until curl http://nrf-service.5gcore.svc.cluster.local:29510; do echo waiting for NRF; sleep 2; done"]
      containers:
      - name: udr
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        image: ilyassifez/5gcore:udr
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29504
        command: ["./udr"]
        args: ["-udrcfg", "../config/udrcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/udrcfg.conf
          name: udrcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: udr5gc-volume
      volumes:
      - name: udrcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/udrcfg.conf
      - name: udr5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: udr-service
spec:
  clusterIP: 10.244.100.4
  selector:
    app: udr
  ports:
    - protocol: TCP
      port: 29504 # Port exposed to the cluster
      targetPort: 29504 # Port on which the pod listens
