apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: webui-service
spec:
  selector:
    nf: webui
  ports:
    - protocol: TCP
      port: 5000 # Port exposed to the cluster
      targetPort: 5000 # Port on which the pod listens
