apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: ausf-deployment
  labels:
    app: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      hostname: ausf
      initContainers:
      - name: init-nrf-service
        image: curlimages/curl:latest
        command: ['sh', '-c', "until curl http://nrf-service.5gcore.svc.cluster.local:29510; do echo waiting for NRF; sleep 2; done"]
      containers:
      - name: ausf
        image: ilyassifez/5gcore:ausf
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        env:
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29509
        command: ["./ausf"]
        args: ["-ausfcfg", "../config/ausfcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/ausfcfg.conf
          name: ausfcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: ausf5gc-volume
      volumes:
      - name: ausfcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/ausfcfg.conf
      - name: ausf5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: ausf-service
spec:
  # clusterIP: 10.244.100.9
  selector:
    app: ausf
  ports:
    - protocol: TCP
      port: 29509 # Port exposed to the cluster
      targetPort: 29509 # Port on which the pod listens
