apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: nrf-deployment
  labels:
    app: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      hostname: nrf
      initContainers:
      - name: init-mongo-service
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mongo-service.5gcore.svc.cluster.local; do echo waiting for mongo; sleep 2; done"]
      containers:
      - name: nrf
        image: ilyassifez/5gcore:nrf
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        env:
        - name: DB_URI
          value: mongodb://db/free5gc
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 29510
        command: ["./nrf"]
        args: ["-nrfcfg", "../config/nrfcfg.conf"]
        volumeMounts:
        - mountPath: /free5gc/config/nrfcfg.conf
          name: nrfcfg-volume
        - mountPath: /free5gc/config/free5GC.conf
          name: nrf5gc-volume
      volumes:
      - name: nrfcfg-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/nrfcfg.conf
      - name: nrf5gc-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/free5GC.conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: nrf-service
spec:
  clusterIP: 10.244.100.12
  selector:
    app: nrf
  ports:
    - port: 29510 # Port exposed to the cluster
      protocol: TCP
      targetPort: 29510 # Port on which the pod listens
