apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: upf1-deployment
  labels:
    app: upf1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf1
  template:
    metadata:
      labels:
        app: upf1
    spec:
      hostname: upf1
      initContainers:
      - name: init-nrf-service
        image: curlimages/curl:latest
        command: ['sh', '-c', "until curl http://nrf-service.5gcore.svc.cluster.local:29510; do echo waiting for NRF; sleep 2; done"]
      containers:
      - name: upf1
        image: ilyassifez/5gcore:upf-1
        command: ["./free5gc-upfd"]
        args: ["-f", "../config/upfcfg.yaml"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        volumeMounts:
        - mountPath: /free5gc/config/upfcfg.yaml
          name: upfcfg1-volume
      volumes:
      - name: upfcfg1-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/upfcfg1.yaml
