apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 5gcore
  name: upfb-deployment
  labels:
    app: upfb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upfb
  template:
    metadata:
      labels:
        app: upfb
    spec:
      hostname: upfb
      initContainers:
      - name: init-nrf-service
        image: curlimages/curl:latest
        command: ['sh', '-c', "until curl http://nrf-service.5gcore.svc.cluster.local:29510; do echo waiting for NRF; sleep 2; done"]
      containers:
      - name: upfb
        image: ilyassifez/5gcore:upf-b
        command: ["./free5gc-upfd"]
        args: ["-f", "../config/upfcfg.yaml"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        volumeMounts:
        - mountPath: /free5gc/config/upfcfg.yaml
          name: upfcfgb-volume
      volumes:
      - name: upfcfgb-volume
        hostPath:
          # chemin du dossier sur l'hôte
          path: /home/ilyass/5gcore/config/upfcfgb.yaml
