apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.mongo.name }}
  labels:
    app: {{  .Values.mongo.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: {{  .Values.mongo.app }}
  template:
    metadata:
      labels:
        app: {{  .Values.mongo.app }}
    spec:
      {{- if .Values.mongo.initContainers }}
      initContainers:
        {{- toYaml .Values.mongo.initContainers | nindent 8 }}
      {{- end }}
      containers:
      - name: {{  .Values.mongo.app }}
        securityContext:
            {{- toYaml .Values.mongo.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.mongo.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.mongo.env }}
        env:
            {{- toYaml .Values.mongo.env | nindent 8 }}
          {{- end }}
        ports:
        - containerPort: {{  .Values.mongo.containerPort }}
        command:  {{  .Values.mongo.command }}
        args: {{  .Values.mongo.args }}
        volumeMounts:
          {{- toYaml .Values.mongo.volumeMounts | nindent 8 }}
      volumes:
            {{- toYaml .Values.mongo.volumes | nindent 6 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.service.name }}
  namespace: {{ .Values.namespace}}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
      protocol: TCP
  selector:
    app: {{  .Values.mongo.app }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Values.mongo.pv.name }}
spec:
  volumeMode: {{ .Values.mongo.pv.mode }}
  hostPath:
    path: {{ .Values.mongo.pv.path }}
  capacity:
    storage: {{ .Values.mongo.pv.capacity }}
  accessModes:
  {{- toYaml .Values.mongo.pv.accessModes | nindent 2 }}
  persistentVolumeReclaimPolicy: {{ .Values.mongo.pv.reclaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Values.mongo.pvc.name }}
spec:
  accessModes:
  {{- toYaml .Values.mongo.pv.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.mongo.pv.capacity }}
