apiVersion: v1
kind: Service
metadata:
  name: {{ include "5gcore.fullname" . }}
  namespace: {{ .Values.nrf.service.name }}
spec:
  {{- if eq .Values.nrf.service.type "ClusterIP" }}
  clusterIP: {{ .Values.nrf.service.clusterIP }}
  {{- end }}
  type: {{ .Values.nrf.service.type }}
  ports:
    - port: {{ .Values.nrf.service.port }}
      targetPort: {{ .Values.nrf.service.targetPort }}
      protocol: TCP
  selector:
    app: {{  .Values.nrf.app }}
