apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.pcf.name }}
  labels:
    app: {{  .Values.pcf.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: {{  .Values.pcf.app }}
  template:
    metadata:
      labels:
        app: {{  .Values.pcf.app }}
    spec:
      {{- if .Values.pcf.initContainers }}
      initContainers:
        {{- toYaml .Values.pcf.initContainers | nindent 8 }}
      {{- end }}
      containers:
      - name: {{  .Values.pcf.app }}
        securityContext:
            {{- toYaml .Values.pcf.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.pcf.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.pcf.env }}
        env:
            {{- toYaml .Values.pcf.env | nindent 8 }}
          {{- end }}
        ports:
        - containerPort: {{  .Values.pcf.containerPort }}
        command:  {{  .Values.pcf.command }}
        args: {{  .Values.pcf.args }}
        volumeMounts:
          {{- toYaml .Values.pcf.volumeMounts | nindent 8 }}
      volumes:
            {{- toYaml .Values.pcf.volumes | nindent 6 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pcf.service.name }}
  namespace: {{ .Values.namespace}}
spec:
  type: {{ .Values.pcf.service.type }}
  ports:
    - port: {{ .Values.pcf.service.port }}
      targetPort: {{ .Values.pcf.service.targetPort }}
      protocol: TCP
  selector:
    app: {{  .Values.pcf.app }}
