apiVersion: v1
kind: Service
metadata:
  namespace: 5gcore
  name: mongo-service
spec:
  selector:
    nf: mongo
  ports:
    - protocol: TCP
      port: 27017 # Port exposed to the cluster
      targetPort: 27017 # Port on which the pod listens
